### ISSUE TITLE
Parking Brake Completely Igonored

### ISSUE THREAD

**Issue by THEONEANDONLYPLANE** [YesAviation/747-400#13]
Recently I have been spawning in, and stuck with the plane rolling back due to manual, or parking brakes ignoring my inputs. Is this apart of the systems, or a bug?

**Comment by Airbus5717** [comment]
Why opening an issue when there is a similar one https://github.com/YesAviation/747-400/issues/9

**Comment by THEONEANDONLYPLANE** [comment]
Thats betterpushback not recognizing oarking brake
