### ISSUE TITLE
Sounds and FMC/FMS

### ISSUE THREAD

**Issue by JKprolog** [YesAviation/747-400#18]
First of all, gratz for your great job, you all are too much promising,

what i saw: the external sounds unexists, as well as the "touch" sound on the cookpit buttons AND, yet, the APU sound start instantly when it's started. Also, the FMC/FMS looks like the defaut, once it's different just in the first screen, but it's unable to click on it, being usefull just the default configuration. Well, am i doing something wrong or anything?? Thank you!

**Comment by mSparks43** [comment]
These are all work in progress, master currently has the closest thing to a flyable aircraft, I'm working on general systems on the navigationsystems branch (not currently suitable for flight). Looking forward to WolfAir pushing his sound update myself.

**Comment by JKprolog** [comment]
Oh, nice, pal. I'm very excited to see how it's gonna be like.
