### ISSUE TITLE
X-Plane crash

### ISSUE THREAD

**Issue by goby89** [YesAviation/747-400#19]
Hello , Last week and this week started to have some problems with XLua crash when i connect the Honeycomb yoke  but only when i load this aircraft.
[Log.txt](https://github.com/YesAviation/747-400/files/4570230/Log.txt)

**Comment by mSparks43** [comment]
hmm, the xlua in the plugins folder is not telling the truth about its version....

Delete the win/lin/mac folders in the plugins/xlua folder and copy the plugins/xlua/64 folder from the Laminar C172 

I'll rollback the one on master to default soon

**Comment by mSparks43** [comment]
closing this issue as resolved, if it persists please reopen, open a different issue for any related problems
