### ISSUE TITLE
Avitab is forced on and cannot be turned off

### ISSUE THREAD

**Issue by RGaming007** [YesAviation/747-400#21]
I reinstalled this https://forums.x-plane.org/index.php?/files/file/57656-default-b744-avitab-integration/ and it fixed the issiue comparing the code theres an extra few lines at the bottom that i think are the issue 

the EFB does not respond the the ECS button

**Comment by mSparks43** [comment]
closing this issue as resolved, if it persists please reopen, open a different issue for any related problems
