### ISSUE TITLE
Baro is forced to disagree

### ISSUE THREAD

**Issue by RGaming007** [YesAviation/747-400#23]
Baro disagree notice comes up when both baros are set properly 
![X-Plane Screenshot 2020 06 02 - 11 19 44 15](https://user-images.githubusercontent.com/60050366/83537850-1cfad500-a4c3-11ea-9dd8-d1286750dd26.png)
perly

**Comment by mSparks43** [comment]
replaced B747DR_efis_baro_capt_set_dial_pos - fo 

with 

simDR_altimeter_baro_inHg - fo 

And fixed init function

in fltInst02.lua B747_baro_disagree (N.B. disagree warn takes 60 seconds to display)

**Comment by RGaming007** [comment]
fixed
