### ISSUE TITLE
yesaviaton747max broken

### ISSUE THREAD

**Issue by JoKu249** [YesAviation/747-400#7]
this plane is stupid id doesn't work i get -fps and my sim runs backwards. I think it is installed wrong, i put it in my flightgear custom scenery folder the plane is bad

**Comment by aeroplane73** [comment]
Roger that sir proceed to delete system32 and reinstall x-gear.

**Comment by JoKu249** [comment]
@JoKu249 you're an absolute dipstick why would you put it in custom scenery, it goes in global scenery you silly goose

**Comment by JoKu249** [comment]
@aeroplane73 thanks I'll try

**Comment by slimit75** [comment]
Did you try putting it into the "Recycling Bin" folder of FlightGear? 😉

**Comment by JoKu249** [comment]
@aeroplane73 i deleted my system32 folder like you said and now my computer went all funny please help or i will permaban you from my github issue

**Comment by mSparks43** [comment]
please dont do this. I really dont need this nonesense emailing to me.
